#!/bin/bash
# This is a script which will be added to the PATH and 
# will allow for the creation of new users for the VPN 
# and then will place them in a designated location for 
# the scoreboard to pick up

die () {
    echo >&2 "$@"
    exit 1
}

# Validate permissions and parameters for the script
[ `whoami` == 'root' ] || die "You must be root to do this."
[ "$#" -eq 1 ] || die "1 argument required, $# provided"

config_template='/opt/openvpn_templates/template-client-config'
key_store='/opt/openvpn_keys'
openvpn='/etc/openvpn'
client_name=`echo $1 | sed 's/[^0-9a-zA-Z]*//g'`
if [ -e $key_store/$client_name.zip ] ; then
    i=0
    while [ -e $key_store/$client_name-$i.zip ] ; do
        let i++
    done
    client_name=$client_name-$i
fi

cd $openvpn/easy-rsa
. ./vars
./pkitool $client_name

mkdir /tmp/$client_name
cd /tmp/$client_name
cp $openvpn/easy-rsa/keys/ca.crt "ca-$client_name.crt"
cp $openvpn/easy-rsa/keys/$client_name.key $openvpn/easy-rsa/keys/$client_name.crt .
cp $config_template $client_name.ovpn
cp /etc/opencpn/tc.key tc.key
sed -i -e "s/client1/$client_name/" -e "s/^ca ca.crt/ca ca-$client_name.crt/" $client_name.ovpn
zip $client_name.zip $client_name.ovpn $client_name.crt $client_name.key ca-$client_name.crt tc.key
chmod -R a+rX .
mv $client_name.zip $key_store/$client_name.zip
rm -rf /tmp/$client_name
echo "Generated configuration files are in $key_store/$client_name.zip"