#!/bin/bash

DESC="Start openvpn-watchkeys to watch directory in the background and create keys as needed."
NAME=openvpn-watchkeys
DAEMON=/usr/bin/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
RUN_AS=root

start() {
  start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON --quiet
}

stop() {
  kill -TERM `cat $PIDFILE`
  rm $PIDFILE
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: {start|stop|restart}"
    exit 1
    ;;
esac

exit $?