#!/bin/bash
# This is a script which will be added to the PATH and 
# will allow for the creation of new users for the VPN 
# and then will place them in a designated location for 
# the scoreboard to pick up

die () {
    echo >&2 "$@"
    exit 1
}

# Validate permissions and parameters for the script
[ `whoami` == 'root' ] || die "You must be root to do this."
[ "$#" -eq 1 ] || die "1 argument required, $# provided"

key_store='/opt/openvpn_keys'
openvpn='/etc/openvpn'
client_name=`echo $1 | sed 's/[^0-9a-zA-Z]*//g'`

cd $openvpn/easy-rsa
. ./vars
./revoke-full $client_name

cd $openvpn/easy-rsa/keys

cp crl.pem ../../crl.pem

# Verify that the crl-verify is uncommented.
sed -i 's,#\(crl-verify crl.pem\),\1,g' $openvpn/openvpn.conf

rm $client_name.*
rm -rf /tmp/$client_name
rm -rf $key_store/$client_name.zip

service openvpn restart

echo "Cleanup complete"